# Transformer Fine-tuning Experiments
**DistilBERT + BERT + RoBERTa × 7 source configs = 21 experiments**

Requires GPU runtime. Estimated time: ~6-8 hours on T4.

Place the `data/splits/` folder under `/content/data/splits`. If Colab disconnects, re-run the notebook — completed experiments are skipped automatically.

## 1. Setup

In [10]:
!pip install -q transformers

# === Path Configuration ===
# Place the data/splits folder under /content/data/splits
SPLITS_DIR = "/content/data/splits"
RESULTS_DIR = "/content/results"
MODELS_DIR = "/content/models"

import os
os.makedirs(RESULTS_DIR, exist_ok=True)
os.makedirs(MODELS_DIR, exist_ok=True)

files = os.listdir(SPLITS_DIR)
print(f"Found {len(files)} split files")
assert len(files) >= 21

Found 22 split files


In [15]:
import csv
import random
from collections import Counter
from datetime import datetime

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
)
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import get_linear_schedule_with_warmup

# ====== Config ======
SEED = 42
LABEL_MAP = {"negative": 0, "neutral": 1, "positive": 2}
LABEL_NAMES = ["negative", "neutral", "positive"]

TRANSFORMER_MODELS = {
    "distilbert": "distilbert-base-uncased",
    "bert": "bert-base-uncased",
    "roberta": "roberta-base",
}
TRANSFORMER_MAX_LENGTH_TWEET = 128
TRANSFORMER_MAX_LENGTH_REVIEW = 512
TRANSFORMER_EPOCHS = 4
TRANSFORMER_BATCH_SIZE = 16
TRANSFORMER_LEARNING_RATE = 2e-5
TRANSFORMER_WEIGHT_DECAY = 0.01

ALL_CONFIGS = [
    "twitter", "skytrax", "airlinequality",
    "twitter+skytrax", "twitter+airlinequality", "skytrax+airlinequality",
    "twitter+skytrax+airlinequality"
]

LOG_FILE = os.path.join(RESULTS_DIR, "experiment_log_transformers.csv")

def set_seed(seed=SEED):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False

set_seed()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")

Device: cuda
GPU: NVIDIA A100-SXM4-80GB


## 2. Utilities

In [16]:
def load_split(source_config, split):
    path = os.path.join(SPLITS_DIR, f"{source_config}_{split}.csv")
    texts, labels = [], []
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            texts.append(row["text"])
            labels.append(LABEL_MAP[row["label"]])
    return texts, labels


def get_max_length(source_config):
    return TRANSFORMER_MAX_LENGTH_TWEET if source_config == "twitter" else TRANSFORMER_MAX_LENGTH_REVIEW


def compute_metrics(y_true, y_pred):
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_f1": f1_score(y_true, y_pred, average="macro"),
        "macro_precision": precision_score(y_true, y_pred, average="macro"),
        "macro_recall": recall_score(y_true, y_pred, average="macro"),
        "weighted_f1": f1_score(y_true, y_pred, average="weighted"),
    }


def compute_per_class_metrics(y_true, y_pred):
    result = {}
    for avg in ["macro", "weighted", None]:
        p = precision_score(y_true, y_pred, average=avg, zero_division=0)
        r = recall_score(y_true, y_pred, average=avg, zero_division=0)
        f = f1_score(y_true, y_pred, average=avg, zero_division=0)
        if avg is None:
            for i, name in enumerate(LABEL_NAMES):
                result[f"{name}_precision"] = p[i]
                result[f"{name}_recall"] = r[i]
                result[f"{name}_f1"] = f[i]
        else:
            result[f"{avg}_precision"] = p
            result[f"{avg}_recall"] = r
            result[f"{avg}_f1"] = f
    return result


def get_completed_experiments():
    """Load already-completed experiments from log (for crash recovery)."""
    completed = set()
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                completed.add((row["model"], row["source_config"]))
    return completed

print("Utilities loaded.")

Utilities loaded.


## 3. Dataset & Training

In [17]:
class TextDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx], truncation=True, padding="max_length",
            max_length=self.max_length, return_tensors="pt")
        return {
            "input_ids": enc["input_ids"].squeeze(0),
            "attention_mask": enc["attention_mask"].squeeze(0),
            "label": torch.tensor(self.labels[idx], dtype=torch.long),
        }


def train_epoch(model, loader, optimizer, scheduler):
    model.train()
    total_loss, correct, total = 0, 0, 0
    for batch in loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        outputs.loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        total_loss += outputs.loss.item() * len(labels)
        correct += (outputs.logits.argmax(1) == labels).sum().item()
        total += len(labels)
    return total_loss / total, correct / total


def evaluate_model(model, loader):
    model.eval()
    total_loss, all_preds, all_labels = 0, [], []
    with torch.no_grad():
        for batch in loader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)
            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            total_loss += outputs.loss.item() * len(labels)
            all_preds.extend(outputs.logits.argmax(1).cpu().numpy())
            all_labels.extend(labels.cpu().numpy())
    return total_loss / len(all_labels), np.array(all_preds), np.array(all_labels)

print("Training functions defined.")

Training functions defined.


In [18]:
def run_experiment(model_key, source_config):
    """Fine-tune and evaluate one transformer on one source config."""
    set_seed()
    model_name = TRANSFORMER_MODELS[model_key]
    max_length = get_max_length(source_config)

    print(f"\n{'='*60}")
    print(f"[TRAIN] {model_key.upper()} ({model_name}) | {source_config}")
    print(f"  max_length={max_length}, epochs={TRANSFORMER_EPOCHS}, batch={TRANSFORMER_BATCH_SIZE}")
    print(f"{'='*60}")

    # Load data
    train_texts, train_labels = load_split(source_config, "train")
    val_texts, val_labels = load_split(source_config, "val")
    test_texts, test_labels = load_split(source_config, "test")

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    train_ds = TextDataset(train_texts, train_labels, tokenizer, max_length)
    val_ds = TextDataset(val_texts, val_labels, tokenizer, max_length)
    test_ds = TextDataset(test_texts, test_labels, tokenizer, max_length)

    train_loader = DataLoader(train_ds, batch_size=TRANSFORMER_BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_ds, batch_size=TRANSFORMER_BATCH_SIZE)
    test_loader = DataLoader(test_ds, batch_size=TRANSFORMER_BATCH_SIZE)

    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)
    model = model.to(device)

    optimizer = torch.optim.AdamW(model.parameters(), lr=TRANSFORMER_LEARNING_RATE,
                                  weight_decay=TRANSFORMER_WEIGHT_DECAY)
    total_steps = len(train_loader) * TRANSFORMER_EPOCHS
    scheduler = get_linear_schedule_with_warmup(
        optimizer, num_warmup_steps=int(total_steps * 0.1), num_training_steps=total_steps)

    best_val_f1 = 0
    best_state = None

    for epoch in range(1, TRANSFORMER_EPOCHS + 1):
        train_loss, train_acc = train_epoch(model, train_loader, optimizer, scheduler)
        val_loss, val_preds, val_labels_arr = evaluate_model(model, val_loader)
        val_f1 = f1_score(val_labels_arr, val_preds, average="macro")

        print(f"  Epoch {epoch}/{TRANSFORMER_EPOCHS} | "
              f"train_loss={train_loss:.4f} acc={train_acc:.4f} | "
              f"val_loss={val_loss:.4f} val_f1={val_f1:.4f}")

        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            best_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

    # Restore best and evaluate on test
    model.load_state_dict(best_state)
    model = model.to(device)
    _, test_preds, test_labels_arr = evaluate_model(model, test_loader)

    metrics = compute_metrics(test_labels_arr, test_preds)
    per_class = compute_per_class_metrics(test_labels_arr, test_preds)
    cm = confusion_matrix(test_labels_arr, test_preds)

    print(f"  TEST | Accuracy: {metrics['accuracy']:.4f} | Macro-F1: {metrics['macro_f1']:.4f}")
    print(f"  Confusion Matrix:\n{cm}")

    # Save model to Drive
    save_dir = os.path.join(MODELS_DIR, model_key, source_config)
    os.makedirs(save_dir, exist_ok=True)
    model.cpu().save_pretrained(save_dir)
    tokenizer.save_pretrained(save_dir)
    print(f"  Model saved to {save_dir}")

    # Free GPU memory
    del model, optimizer, scheduler
    torch.cuda.empty_cache()

    return {
        "timestamp": datetime.now().isoformat(timespec="seconds"),
        "model": model_key,
        "source_config": source_config,
        **metrics, **per_class,
    }

print("Experiment function defined.")

Experiment function defined.


## 4. Run All 21 Experiments

Completed experiments are automatically skipped on re-run (crash recovery).

In [19]:
# Load any previously completed experiments
completed = get_completed_experiments()
all_results = []
if os.path.exists(LOG_FILE):
    with open(LOG_FILE, encoding="utf-8") as f:
        all_results = list(csv.DictReader(f))

print(f"Already completed: {len(completed)} experiments")

total_experiments = len(TRANSFORMER_MODELS) * len(ALL_CONFIGS)
exp_num = len(completed)

for model_key in TRANSFORMER_MODELS:
    for source_config in ALL_CONFIGS:
        if (model_key, source_config) in completed:
            print(f"[SKIP] {model_key} | {source_config} (already done)")
            continue

        result = run_experiment(model_key, source_config)
        all_results.append(result)
        exp_num += 1

        # Save after each experiment (crash recovery)
        with open(LOG_FILE, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=list(all_results[0].keys()))
            writer.writeheader()
            writer.writerows(all_results)
        print(f"  [{exp_num}/{total_experiments}] Progress saved.")

print(f"\n{'='*60}")
print(f"DONE: All {total_experiments} experiments completed.")

Already completed: 0 experiments

[TRAIN] DISTILBERT (distilbert-base-uncased) | twitter
  max_length=128, epochs=4, batch=16


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning: 
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(


config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5957 acc=0.7559 | val_loss=0.4297 val_f1=0.7707
  Epoch 2/4 | train_loss=0.3373 acc=0.8740 | val_loss=0.4388 val_f1=0.7808
  Epoch 3/4 | train_loss=0.2178 acc=0.9266 | val_loss=0.5223 val_f1=0.7882
  Epoch 4/4 | train_loss=0.1475 acc=0.9565 | val_loss=0.5987 val_f1=0.7827
  TEST | Accuracy: 0.8333 | Macro-F1: 0.7847
  Confusion Matrix:
[[1202  107   44]
 [  94  295   40]
 [  33   33  258]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/distilbert/twitter
  [1/21] Progress saved.

[TRAIN] DISTILBERT (distilbert-base-uncased) | skytrax
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5542 acc=0.7846 | val_loss=0.4580 val_f1=0.6390
  Epoch 2/4 | train_loss=0.4008 acc=0.8528 | val_loss=0.4561 val_f1=0.6902
  Epoch 3/4 | train_loss=0.3094 acc=0.8945 | val_loss=0.4998 val_f1=0.7065
  Epoch 4/4 | train_loss=0.2331 acc=0.9267 | val_loss=0.5705 val_f1=0.7091
  TEST | Accuracy: 0.8183 | Macro-F1: 0.6942
  Confusion Matrix:
[[1556  231   97]
 [ 232  217  204]
 [  44  196 2750]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/distilbert/skytrax
  [2/21] Progress saved.

[TRAIN] DISTILBERT (distilbert-base-uncased) | airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5155 acc=0.7912 | val_loss=0.4333 val_f1=0.6208
  Epoch 2/4 | train_loss=0.3835 acc=0.8426 | val_loss=0.4530 val_f1=0.5899
  Epoch 3/4 | train_loss=0.3018 acc=0.8835 | val_loss=0.4967 val_f1=0.6290
  Epoch 4/4 | train_loss=0.2311 acc=0.9177 | val_loss=0.5456 val_f1=0.6122
  TEST | Accuracy: 0.8264 | Macro-F1: 0.6340
  Confusion Matrix:
[[2105   56  252]
 [  65   47  114]
 [  76   18  614]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/distilbert/airlinequality
  [3/21] Progress saved.

[TRAIN] DISTILBERT (distilbert-base-uncased) | twitter+skytrax
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5516 acc=0.7851 | val_loss=0.4468 val_f1=0.7175
  Epoch 2/4 | train_loss=0.3858 acc=0.8586 | val_loss=0.4502 val_f1=0.7452
  Epoch 3/4 | train_loss=0.2902 acc=0.8993 | val_loss=0.5117 val_f1=0.7488
  Epoch 4/4 | train_loss=0.2168 acc=0.9313 | val_loss=0.5974 val_f1=0.7443
  TEST | Accuracy: 0.8296 | Macro-F1: 0.7495
  Confusion Matrix:
[[2776  301  160]
 [ 320  493  269]
 [  90  161 3063]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/distilbert/twitter+skytrax
  [4/21] Progress saved.

[TRAIN] DISTILBERT (distilbert-base-uncased) | twitter+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5321 acc=0.7822 | val_loss=0.4557 val_f1=0.7057
  Epoch 2/4 | train_loss=0.3691 acc=0.8518 | val_loss=0.4352 val_f1=0.7173
  Epoch 3/4 | train_loss=0.2785 acc=0.8944 | val_loss=0.4836 val_f1=0.7228
  Epoch 4/4 | train_loss=0.2086 acc=0.9248 | val_loss=0.5602 val_f1=0.7166
  TEST | Accuracy: 0.8295 | Macro-F1: 0.7303
  Confusion Matrix:
[[3372  136  258]
 [ 188  336  131]
 [ 141   76  815]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/distilbert/twitter+airlinequality
  [5/21] Progress saved.

[TRAIN] DISTILBERT (distilbert-base-uncased) | skytrax+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5465 acc=0.7911 | val_loss=0.4528 val_f1=0.6666
  Epoch 2/4 | train_loss=0.4020 acc=0.8504 | val_loss=0.4548 val_f1=0.6972
  Epoch 3/4 | train_loss=0.3092 acc=0.8885 | val_loss=0.5155 val_f1=0.7013
  Epoch 4/4 | train_loss=0.2273 acc=0.9226 | val_loss=0.5913 val_f1=0.7089
  TEST | Accuracy: 0.8294 | Macro-F1: 0.7210
  Confusion Matrix:
[[3687  275  335]
 [ 271  361  247]
 [ 156  230 3312]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/distilbert/skytrax+airlinequality
  [6/21] Progress saved.

[TRAIN] DISTILBERT (distilbert-base-uncased) | twitter+skytrax+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     | 
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED | 
vocab_layer_norm.bias   | UNEXPECTED | 
vocab_projector.bias    | UNEXPECTED | 
vocab_layer_norm.weight | UNEXPECTED | 
vocab_transform.weight  | UNEXPECTED | 
classifier.bias         | MISSING    | 
pre_classifier.bias     | MISSING    | 
pre_classifier.weight   | MISSING    | 
classifier.weight       | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5451 acc=0.7887 | val_loss=0.4530 val_f1=0.7225
  Epoch 2/4 | train_loss=0.3969 acc=0.8523 | val_loss=0.4491 val_f1=0.7272
  Epoch 3/4 | train_loss=0.3021 acc=0.8917 | val_loss=0.5133 val_f1=0.7315
  Epoch 4/4 | train_loss=0.2254 acc=0.9240 | val_loss=0.5844 val_f1=0.7402
  TEST | Accuracy: 0.8266 | Macro-F1: 0.7374
  Confusion Matrix:
[[4921  353  376]
 [ 398  589  321]
 [ 201  255 3566]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/distilbert/twitter+skytrax+airlinequality
  [7/21] Progress saved.

[TRAIN] BERT (bert-base-uncased) | twitter
  max_length=128, epochs=4, batch=16


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5675 acc=0.7618 | val_loss=0.5000 val_f1=0.7289
  Epoch 2/4 | train_loss=0.3063 acc=0.8894 | val_loss=0.4942 val_f1=0.7772
  Epoch 3/4 | train_loss=0.1787 acc=0.9456 | val_loss=0.5803 val_f1=0.7899
  Epoch 4/4 | train_loss=0.0977 acc=0.9727 | val_loss=0.6761 val_f1=0.7889
  TEST | Accuracy: 0.8310 | Macro-F1: 0.7730
  Confusion Matrix:
[[1229   84   40]
 [ 117  267   45]
 [  32   38  254]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/bert/twitter
  [8/21] Progress saved.

[TRAIN] BERT (bert-base-uncased) | skytrax
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5500 acc=0.7822 | val_loss=0.4963 val_f1=0.6225
  Epoch 2/4 | train_loss=0.3809 acc=0.8608 | val_loss=0.4327 val_f1=0.7136
  Epoch 3/4 | train_loss=0.2723 acc=0.9078 | val_loss=0.5068 val_f1=0.7073
  Epoch 4/4 | train_loss=0.1896 acc=0.9429 | val_loss=0.6895 val_f1=0.7086
  TEST | Accuracy: 0.8270 | Macro-F1: 0.7111
  Confusion Matrix:
[[1522  240  122]
 [ 181  245  227]
 [  32  154 2804]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/bert/skytrax
  [9/21] Progress saved.

[TRAIN] BERT (bert-base-uncased) | airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5134 acc=0.7875 | val_loss=0.4584 val_f1=0.5777
  Epoch 2/4 | train_loss=0.3731 acc=0.8475 | val_loss=0.4413 val_f1=0.6012
  Epoch 3/4 | train_loss=0.2720 acc=0.8972 | val_loss=0.5267 val_f1=0.6316
  Epoch 4/4 | train_loss=0.1811 acc=0.9366 | val_loss=0.6475 val_f1=0.6274
  TEST | Accuracy: 0.8243 | Macro-F1: 0.6616
  Confusion Matrix:
[[2124   80  209]
 [  73   82   71]
 [  92   63  553]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/bert/airlinequality
  [10/21] Progress saved.

[TRAIN] BERT (bert-base-uncased) | twitter+skytrax
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5448 acc=0.7864 | val_loss=0.4282 val_f1=0.7524
  Epoch 2/4 | train_loss=0.3662 acc=0.8672 | val_loss=0.4332 val_f1=0.7487
  Epoch 3/4 | train_loss=0.2581 acc=0.9139 | val_loss=0.5300 val_f1=0.7549
  Epoch 4/4 | train_loss=0.1803 acc=0.9460 | val_loss=0.6495 val_f1=0.7544
  TEST | Accuracy: 0.8305 | Macro-F1: 0.7494
  Confusion Matrix:
[[2778  302  157]
 [ 334  489  259]
 [  80  162 3072]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/bert/twitter+skytrax
  [11/21] Progress saved.

[TRAIN] BERT (bert-base-uncased) | twitter+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5219 acc=0.7828 | val_loss=0.4284 val_f1=0.7316
  Epoch 2/4 | train_loss=0.3522 acc=0.8620 | val_loss=0.4815 val_f1=0.6776
  Epoch 3/4 | train_loss=0.2483 acc=0.9081 | val_loss=0.5081 val_f1=0.7224
  Epoch 4/4 | train_loss=0.1702 acc=0.9437 | val_loss=0.6241 val_f1=0.7246
  TEST | Accuracy: 0.8240 | Macro-F1: 0.7265
  Confusion Matrix:
[[3340  146  280]
 [ 200  332  123]
 [ 149   62  821]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/bert/twitter+airlinequality
  [12/21] Progress saved.

[TRAIN] BERT (bert-base-uncased) | skytrax+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5420 acc=0.7917 | val_loss=0.4569 val_f1=0.6158
  Epoch 2/4 | train_loss=0.3856 acc=0.8564 | val_loss=0.4518 val_f1=0.7043
  Epoch 3/4 | train_loss=0.2715 acc=0.9057 | val_loss=0.5572 val_f1=0.7049
  Epoch 4/4 | train_loss=0.1864 acc=0.9419 | val_loss=0.6738 val_f1=0.7124
  TEST | Accuracy: 0.8340 | Macro-F1: 0.7316
  Confusion Matrix:
[[3732  254  311]
 [ 262  389  228]
 [ 173  245 3280]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/bert/skytrax+airlinequality
  [13/21] Progress saved.

[TRAIN] BERT (bert-base-uncased) | twitter+skytrax+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     | 
-------------------------------------------+------------+-
cls.seq_relationship.weight                | UNEXPECTED | 
cls.predictions.transform.dense.weight     | UNEXPECTED | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED | 
cls.predictions.transform.dense.bias       | UNEXPECTED | 
cls.seq_relationship.bias                  | UNEXPECTED | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED | 
cls.predictions.bias                       | UNEXPECTED | 
classifier.bias                            | MISSING    | 
classifier.weight                          | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5388 acc=0.7897 | val_loss=0.4722 val_f1=0.6874
  Epoch 2/4 | train_loss=0.3813 acc=0.8595 | val_loss=0.4437 val_f1=0.7328
  Epoch 3/4 | train_loss=0.2655 acc=0.9079 | val_loss=0.5201 val_f1=0.7376
  Epoch 4/4 | train_loss=0.1817 acc=0.9425 | val_loss=0.6672 val_f1=0.7469
  TEST | Accuracy: 0.8311 | Macro-F1: 0.7494
  Confusion Matrix:
[[4945  361  344]
 [ 366  648  294]
 [ 221  268 3533]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/bert/twitter+skytrax+airlinequality
  [14/21] Progress saved.

[TRAIN] ROBERTA (roberta-base) | twitter
  max_length=128, epochs=4, batch=16


config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 
classifier.dense.bias           | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5655 acc=0.7795 | val_loss=0.4147 val_f1=0.7756
  Epoch 2/4 | train_loss=0.3452 acc=0.8755 | val_loss=0.3788 val_f1=0.8145
  Epoch 3/4 | train_loss=0.2336 acc=0.9221 | val_loss=0.5008 val_f1=0.8122
  Epoch 4/4 | train_loss=0.1716 acc=0.9495 | val_loss=0.5462 val_f1=0.8056
  TEST | Accuracy: 0.8561 | Macro-F1: 0.8055
  Confusion Matrix:
[[1257   59   37]
 [ 116  273   40]
 [  23   28  273]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/roberta/twitter
  [15/21] Progress saved.

[TRAIN] ROBERTA (roberta-base) | skytrax
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 
classifier.dense.bias           | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5336 acc=0.7943 | val_loss=0.4369 val_f1=0.6613
  Epoch 2/4 | train_loss=0.4032 acc=0.8530 | val_loss=0.4552 val_f1=0.6994
  Epoch 3/4 | train_loss=0.3294 acc=0.8880 | val_loss=0.4464 val_f1=0.7247
  Epoch 4/4 | train_loss=0.2647 acc=0.9171 | val_loss=0.5311 val_f1=0.7275
  TEST | Accuracy: 0.8344 | Macro-F1: 0.7209
  Confusion Matrix:
[[1580  204  100]
 [ 214  253  186]
 [  38  173 2779]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/roberta/skytrax
  [16/21] Progress saved.

[TRAIN] ROBERTA (roberta-base) | airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 
classifier.dense.bias           | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5044 acc=0.8006 | val_loss=0.4507 val_f1=0.6121
  Epoch 2/4 | train_loss=0.3865 acc=0.8429 | val_loss=0.4642 val_f1=0.5831
  Epoch 3/4 | train_loss=0.3121 acc=0.8774 | val_loss=0.4919 val_f1=0.6594
  Epoch 4/4 | train_loss=0.2425 acc=0.9114 | val_loss=0.5612 val_f1=0.6500
  TEST | Accuracy: 0.8303 | Macro-F1: 0.6545
  Confusion Matrix:
[[2118   60  235]
 [  68   62   96]
 [  77   32  599]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/roberta/airlinequality
  [17/21] Progress saved.

[TRAIN] ROBERTA (roberta-base) | twitter+skytrax
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 
classifier.dense.bias           | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5237 acc=0.7982 | val_loss=0.4401 val_f1=0.7335
  Epoch 2/4 | train_loss=0.3920 acc=0.8603 | val_loss=0.4433 val_f1=0.7552
  Epoch 3/4 | train_loss=0.3144 acc=0.8916 | val_loss=0.4395 val_f1=0.7747
  Epoch 4/4 | train_loss=0.2498 acc=0.9210 | val_loss=0.5179 val_f1=0.7704
  TEST | Accuracy: 0.8424 | Macro-F1: 0.7638
  Confusion Matrix:
[[2822  255  160]
 [ 311  505  266]
 [  59  152 3103]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/roberta/twitter+skytrax
  [18/21] Progress saved.

[TRAIN] ROBERTA (roberta-base) | twitter+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 
classifier.dense.bias           | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5111 acc=0.7959 | val_loss=0.4395 val_f1=0.7112
  Epoch 2/4 | train_loss=0.3722 acc=0.8558 | val_loss=0.4309 val_f1=0.7240
  Epoch 3/4 | train_loss=0.2945 acc=0.8893 | val_loss=0.4516 val_f1=0.7438
  Epoch 4/4 | train_loss=0.2283 acc=0.9200 | val_loss=0.5137 val_f1=0.7402
  TEST | Accuracy: 0.8339 | Macro-F1: 0.7336
  Confusion Matrix:
[[3354  126  286]
 [ 181  326  148]
 [  85   80  867]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/roberta/twitter+airlinequality
  [19/21] Progress saved.

[TRAIN] ROBERTA (roberta-base) | skytrax+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 
classifier.dense.bias           | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5281 acc=0.8009 | val_loss=0.4555 val_f1=0.7026
  Epoch 2/4 | train_loss=0.4074 acc=0.8480 | val_loss=0.4296 val_f1=0.7258
  Epoch 3/4 | train_loss=0.3339 acc=0.8789 | val_loss=0.4456 val_f1=0.7277
  Epoch 4/4 | train_loss=0.2643 acc=0.9079 | val_loss=0.5067 val_f1=0.7266
  TEST | Accuracy: 0.8381 | Macro-F1: 0.7258
  Confusion Matrix:
[[3733  248  316]
 [ 273  340  266]
 [ 165  169 3364]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/roberta/skytrax+airlinequality
  [20/21] Progress saved.

[TRAIN] ROBERTA (roberta-base) | twitter+skytrax+airlinequality
  max_length=512, epochs=4, batch=16


Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     | 
--------------------------------+------------+-
lm_head.layer_norm.weight       | UNEXPECTED | 
lm_head.bias                    | UNEXPECTED | 
lm_head.dense.bias              | UNEXPECTED | 
lm_head.dense.weight            | UNEXPECTED | 
lm_head.layer_norm.bias         | UNEXPECTED | 
roberta.embeddings.position_ids | UNEXPECTED | 
classifier.dense.weight         | MISSING    | 
classifier.out_proj.bias        | MISSING    | 
classifier.out_proj.weight      | MISSING    | 
classifier.dense.bias           | MISSING    | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.


  Epoch 1/4 | train_loss=0.5283 acc=0.7996 | val_loss=0.4299 val_f1=0.7437
  Epoch 2/4 | train_loss=0.4031 acc=0.8501 | val_loss=0.4430 val_f1=0.7322
  Epoch 3/4 | train_loss=0.3225 acc=0.8840 | val_loss=0.4743 val_f1=0.7466
  Epoch 4/4 | train_loss=0.2525 acc=0.9140 | val_loss=0.5206 val_f1=0.7566
  TEST | Accuracy: 0.8362 | Macro-F1: 0.7507
  Confusion Matrix:
[[4956  322  372]
 [ 378  620  310]
 [ 162  255 3605]]


Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Model saved to /content/models/roberta/twitter+skytrax+airlinequality
  [21/21] Progress saved.

DONE: All 21 experiments completed.


## 5. Results Summary

In [20]:
# Reload from file to get clean data
with open(LOG_FILE, encoding="utf-8") as f:
    final_results = list(csv.DictReader(f))

print(f"{'Model':<12} {'Source Config':<35} {'Accuracy':>10} {'Macro-F1':>10}")
print("=" * 72)
for r in final_results:
    print(f"{r['model']:<12} {r['source_config']:<35} {float(r['accuracy']):>10.4f} {float(r['macro_f1']):>10.4f}")

best = max(final_results, key=lambda x: float(x["macro_f1"]))
print(f"\nBest: {best['model']} | {best['source_config']} | Macro-F1: {float(best['macro_f1']):.4f}")

Model        Source Config                         Accuracy   Macro-F1
distilbert   twitter                                 0.8333     0.7847
distilbert   skytrax                                 0.8183     0.6942
distilbert   airlinequality                             0.8264     0.6340
distilbert   twitter+skytrax                         0.8296     0.7495
distilbert   twitter+airlinequality                     0.8295     0.7303
distilbert   skytrax+airlinequality                     0.8294     0.7210
distilbert   twitter+skytrax+airlinequality             0.8266     0.7374
bert         twitter                                 0.8310     0.7730
bert         skytrax                                 0.8270     0.7111
bert         airlinequality                             0.8243     0.6616
bert         twitter+skytrax                         0.8305     0.7494
bert         twitter+airlinequality                     0.8240     0.7265
bert         skytrax+airlinequality                     0.8

## 6. Download Results

In [22]:
import subprocess
#subprocess.run(["zip", "-r", "/content/results_all.zip", "/content/results", "/content/models"], check=True)
subprocess.run(["zip", "-r", "/content/models_bert_skytrax.zip", "/content/models/bert/skytrax"], check=True)
subprocess.run(["zip", "-r", "/content/models_bert_skytrax_airlinequality.zip", "/content/models/bert/skytrax+airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_bert_airlinequality.zip", "/content/models/bert/airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_bert_twitter.zip", "/content/models/bert/twitter"], check=True)
subprocess.run(["zip", "-r", "/content/models_bert_twitter_skytrax.zip", "/content/models/bert/twitter+skytrax"], check=True)
subprocess.run(["zip", "-r", "/content/models_bert_twitter_skytrax_airlinequality.zip", "/content/models/bert/twitter+skytrax+airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_bert_twitter_airlinequality.zip", "/content/models/bert/twitter+airlinequality"], check=True)

subprocess.run(["zip", "-r", "/content/models_distilbert_skytrax.zip", "/content/models/distilbert/skytrax"], check=True)
subprocess.run(["zip", "-r", "/content/models_distilbert_skytrax_airlinequality.zip", "/content/models/distilbert/skytrax+airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_distilbert_airlinequality.zip", "/content/models/distilbert/airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_distilbert_twitter.zip", "/content/models/distilbert/twitter"], check=True)
subprocess.run(["zip", "-r", "/content/models_distilbert_twitter_skytrax.zip", "/content/models/distilbert/twitter+skytrax"], check=True)
subprocess.run(["zip", "-r", "/content/models_distilbert_twitter_skytrax_airlinequality.zip", "/content/models/distilbert/twitter+skytrax+airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_distilbert_twitter_airlinequality.zip", "/content/models/bert/twitter+airlinequality"], check=True)

subprocess.run(["zip", "-r", "/content/models_roberta_skytrax.zip", "/content/models/roberta/skytrax"], check=True)
subprocess.run(["zip", "-r", "/content/models_roberta_skytrax_airlinequality.zip", "/content/models/roberta/skytrax+airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_roberta_airlinequality.zip", "/content/models/roberta/airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_roberta_twitter.zip", "/content/models/roberta/twitter"], check=True)
subprocess.run(["zip", "-r", "/content/models_roberta_twitter_skytrax.zip", "/content/models/roberta/twitter+skytrax"], check=True)
subprocess.run(["zip", "-r", "/content/models_roberta_twitter_skytrax_airlinequality.zip", "/content/models/roberta/twitter+skytrax+airlinequality"], check=True)
subprocess.run(["zip", "-r", "/content/models_roberta_twitter_airlinequality.zip", "/content/models/roberta/twitter+airlinequality"], check=True)

print("Zip created: /content/results_all.zip")
print("This contains all results and models. Download from the file explorer.")

Zip created: /content/results_all.zip
This contains all results and models. Download from the file explorer.


In [23]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive
